In [1]:
# Defining the adjaceny matix 
import numpy as np 
A = np.array([ 
	[0, 1, 1, 0, 0, 0, 0, 0, 1, 1], 
	[1, 0, 1, 0, 0, 0, 0, 0, 0, 0], 
	[1, 1, 0, 0, 0, 0, 0, 0, 0, 0], 
	[0, 0, 0, 0, 1, 1, 0, 0, 0, 0], 
	[0, 0, 0, 1, 0, 1, 0, 0, 0, 0], 
	[0, 0, 0, 1, 1, 0, 1, 1, 0, 0], 
	[0, 0, 0, 0, 0, 1, 0, 1, 0, 0], 
	[0, 0, 0, 0, 0, 1, 1, 0, 0, 0], 
	[1, 0, 0, 0, 0, 0, 0, 0, 0, 1], 
	[1, 0, 0, 0, 0, 0, 0, 0, 1, 0]]) 


In [3]:
D = np.diag(A.sum(axis=1)) 
print(D) 


[[4 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 2]]


In [5]:
L = D-A 
print(L) 


[[ 4 -1 -1  0  0  0  0  0 -1 -1]
 [-1  2 -1  0  0  0  0  0  0  0]
 [-1 -1  2  0  0  0  0  0  0  0]
 [ 0  0  0  2 -1 -1  0  0  0  0]
 [ 0  0  0 -1  2 -1  0  0  0  0]
 [ 0  0  0 -1 -1  4 -1 -1  0  0]
 [ 0  0  0  0  0 -1  2 -1  0  0]
 [ 0  0  0  0  0 -1 -1  2  0  0]
 [-1  0  0  0  0  0  0  0  2 -1]
 [-1  0  0  0  0  0  0  0 -1  2]]
